package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"log_parser/cmd/logFilter/helper"
	"log_parser/model"
	"log_parser/pkg/filter"
	"os"
)

func main() {
	inputFile := flag.String("in", "parsed_logs.json", "Input JSON file generated by log_parser (required)")
	level := flag.String("level", "", "Comma separated list of log levels")
	component := flag.String("component", "", "Comma separated list of components")
	host := flag.String("host", "", "Comma separated list of hosts")
	reqID := flag.String("reqID", "", "Comma separated list of requestIDs")
	startTimeString := flag.String("after", "", "Filter by start time [2006-01-02 15:04:05]")
	endTimeString := flag.String("before", "", "Filter by end time [2006-01-02 15:04:05]")
	flag.Parse()

	file, err := os.ReadFile(*inputFile)
	if err != nil {
		slog.Error("Failed to open JSON file", "error", err)
	}

	var segments []model.Segment
	err = json.Unmarshal(file, &segments)
	if err != nil {
		slog.Error("Failed to unmarshal!")
	}

	levels := helper.Split(*level)
	components := helper.Split(*component)
	hosts := helper.Split(*host)
	reqIDs := helper.Split(*reqID)

	startTime := helper.ParseTimeFlag(*startTimeString)
	endTime := helper.ParseTimeFlag(*endTimeString)

	filteredLogs := filter.FilterLogs(model.LogStore{Segments: segments}, levels, components, hosts, reqIDs, startTime, endTime)
	fmt.Printf("Found %d matching entries\n", len(filteredLogs))
	for _, entry := range filteredLogs {
		fmt.Println(entry.Log)
	}
}
